### ISSUE TITLE
An easier way to enable ublksrv log functions

### ISSUE THREAD

**Issue by old-memories** [ming1/ubdsrv#41]
Hi Ming,

I find that ublksrv provides log functions but it is disabled by default. Is there any easier ways to enable them? 

We could add "-DDEBUG" in CFLAGS while running ./configure but I think this is not handy for users. Or we could add these steps in README.

``` C
#ifdef DEBUG
static inline void ublksrv_log(int priority, const char *fmt, ...)
{
    va_list ap;

    va_start(ap, fmt);
    vsyslog(priority, fmt, ap);
}

static inline void ublksrv_printf(FILE *stream, const char *fmt, ...)
{
    va_list ap;

    va_start(ap, fmt);
    vfprintf(stream, fmt, ap);
}
#else
static inline void ublksrv_log(int priority, const char *fmt, ...) { }
static inline void ublksrv_printf(FILE *stream, const char *fmt, ...) {}
#endif
```

**Comment by ming1** [comment]
Hi Ziyang,

OK, we could add ./configure option for enabling debug switch,
will do that and document in readme.

thanks,

**Comment by ming1** [comment]
BTW, ublksrv log is improved now.

But, not support runtime logging, so for any logging still need
to ./configure --enable-debug for passing -DDEBUG.

The improvement is  adding debug masks for grouping
logging info by passing --debug_mask to 'ublk add', see 
each kind of debug level: UBLK_DBG_* in include/ublksrv_utils.h
