### ISSUE TITLE
README is missing references.

### ISSUE THREAD

**Issue by sbates130272** [ming1/ubdsrv#5]
The README currently references a number of external links but only one reference is actually given?

e.g. "Also looks linux-mm can't support zero copy for this case yet[3]."

**Comment by old-memories** [comment]
Yes, README is missing some links. I get some links from a early kernel patch:
https://lore.kernel.org/all/20220517055358.3164431-1-ming.lei@redhat.com/

Here is some useful links

[2] qcow2 kernel driver attempt
https://www.spinics.net/lists/kernel/msg4292965.html
https://patchwork.kernel.org/project/linux-block/cover/20190823225619.15530-1-development@manuel-bentele.de/#22841183

[3] [LSF/MM/BPF TOPIC] block drivers in user space
https://lore.kernel.org/linux-block/87tucsf0sr.fsf@collabora.com/

[4] Follow up on UBD discussion
https://lore.kernel.org/linux-block/YnsW+utCrosF0lvm@T590/#r

**Comment by ming1** [comment]
> 

Fixed now!
