### ISSUE TITLE
Will be v1.1 released?

### ISSUE THREAD

**Issue by vt-alt** [ming1/ubdsrv#58]
`v1.1-rc1` is released at 2023-02-04. Will v1.1 be released anytime soon?

ps. I am considering if this worth to build ubdsrv package for ALT Linux distributions.
See who currently builds it https://repology.org/project/ubdsrv/versions
Distributions rarely build form master or random commit and usually build from a release tag.

**Comment by ming1** [comment]
Hello,

Now v1.1 is released, and I think you can build it against v1.1.

Thanks,

**Comment by vt-alt** [comment]
@ming1  That's great! Thanks!
