### ISSUE TITLE
Should we enable gnutls?

### ISSUE THREAD

**Issue by vt-alt** [ming1/ubdsrv#59]
Is gnutls supposed to be enabled?

Currently `nbd/nbd-client.c` have:

```
#include "cliserv.h"

#if HAVE_GNUTLS && !defined(NOTLS)
#include "crypto-gnutls.h"
#endif
```
and `nbd/cliserv.h` have:
```
#define NOTLS
```
Is this intentional?

**Comment by ming1** [comment]
Hello,

Yeah, it is intentional, because nbd doesn't support TLS yet.

Thanks,

**Comment by vt-alt** [comment]
Thanks for the answer!
